# Generated by Django 5.2.5 on 2025-09-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_ventaproducto_precio_unitario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='empresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
