FROM node:20
WORKDIR /app
RUN npm i -g @angular/cli
# node_modules se instala al construir y se mantiene en volumen
COPY pos-frontend/package*.json ./
RUN npm ci
# El código se montará por volumen para hot-reload
EXPOSE 4200
CMD ng serve --host 0.0.0.0 --port 4200 --poll 2000
