# Generated by Django 5.2.5 on 2025-09-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='empresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cod_barras',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(fields=('empresa', 'cod_barras'), name='unique_empresa_cod_barras'),
        ),
    ]
